title: Mind Forge

baseurl: 
url: http://mindforge.kr

google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Default description in social shares for the jekyll-seo-tag gem
description: Mind Forge 웹사이트 입니다.
comp_name: Mind Forge
comp_logo-wide: logo-wide.png
comp_logo-long: logo-long.png

# Author details for the jekyll-seo-tag gem
author:
  name:
  email:
  twitter: # twitter username without the @ symbol

# Social details for the jekyll-seo-tag gem
# social:
#   name: Urban Template
#   links:
#     - https://github.com/CloudCannon/urban-jekyll-template

timezone: Asia/Seoul # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

collections:
  #staff_members:
    #output: false
  clients:
    output: true

paginate: 10
paginate_path: "/blog/:num/"
permalink: pretty

jekyll-archives:
  enabled:
    - "categories"

plugins:
  - "jekyll-feed"
  - "jekyll-seo-tag"
  - "jekyll-paginate"
  - "jekyll-archives"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

include: 
  - _pages

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      _options:
        content:
          width: 960
          height: 2000
  - scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image_path:
          width: 600
          height: 600
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "index.html"
      type: "pages"
    values:
      layout: "default"

# -----------
# CloudCannon
social_icons:
  - Facebook
  - Instagram
  - LinkedIn
  - Pinterest
  - Tumblr
  - Twitter
  - YouTube
  - RSS
